Permissions Layer for Versioned store
Joystream/substrate-versioned-store-permissions-module pull request #1
Opened 2019-10-15 07:48 UTC by mnaamani

WIP:

Implements https://github.com/Joystream/joystream/issues/92

- [x] Basic Implementation
 - [ ] Update versioned store - `Entity.class_id`, `ClassPropertyValue.value`, `ClassPeropertyValue.in_class_index` are private fields (add some helper methods instead of direct access)
- [ ] Tests

2019-10-22 11:54 UTC, siman commented
Seems like there is a typo in a file name: `principles.rs` -> `principals.rs`

2019-10-29 12:02 UTC, bedeho commented
I have not reviwed, let me know if I should, can make sense before you start making new major changes that we planned.

However I wanted to make a small ask, could we change from "participant" to "credential" ? You the reason is that the mapping of the id corresponds to such disperate actor(s)

- the lead
- one or more curators
- one or more members/channel owners
- any member

so really, what is being furnished when trying to write to the store is not so much your ID as a participant, but a sort of credential for what it is you want to do, and the WG holds the underlying information about what account actually holds what credential at any given time. That naming makes more sense to me.

Let me know what you think.

2019-11-06 08:12 UTC, mnaamani commented
I think you might be right about the naming of the id. Here is some [background about security terminology](https://docs.oracle.com/javase/7/docs/technotes/guides/security/jgss/tutorials/glossary.html) related to prinicpals,subjects,authentication and credentials.

referencing from link above: "Credentials might also contain data that enables the subject to perform certain activities", it seems to translate well to what these IDs represent.

2019-12-24 11:08 UTC, siman requested changes

2019-12-24 11:08 UTC, siman commented on src/permissions.rs
> +    /// root origin can update and delete entities of this class.
We cannot delete entities yet. (Will we be able to do this in the future? Not decided yet)
```suggestion
    /// root origin can update entities of this class.
```

2019-12-24 11:08 UTC, siman commented on src/permissions.rs
> +    pub delete: EntityPrincipalSet<AccountId, GroupId>,
Versioned store doesn't have a functionality to delete something on Entity.
I commented it out as @bedeho asked
```suggestion
```

2019-12-24 11:08 UTC, siman commented on src/tests.rs
> +            delete: EntityPrincipalSet::new(),
Versioned store doesn't have a functionality to delete something on Entity.
I commented it out as @bedeho asked
```suggestion
```

2019-12-24 11:08 UTC, siman commented on src/tests.rs
> +        // default permissions give entity owner permission to update and delete
Versioned store doesn't have a functionality to delete something on Entity.
```suggestion
        // default permissions give entity owner permission to update
```

2019-12-24 11:08 UTC, siman commented on src/tests.rs
> +        assert!(class_permissions.entity_permissions.delete.is_empty());
```suggestion
```

2019-12-24 11:08 UTC, siman commented on src/tests.rs
> +            delete: EntityPrincipalSet::from(vec![EntityPrincipal::Base(BasePrincipal::Account(
Delete `delete` entry

2019-12-24 11:08 UTC, siman commented on src/tests.rs
> +            delete: EntityPrincipalSet::from(vec![EntityPrincipal::Base(BasePrincipal::Account(
Delete `delete` entry

2019-12-24 11:08 UTC, siman commented on src/permissions.rs
> +    pub fn can_add_schema(
I suggest improving naming to fully reflect for what method this check is used.
```suggestion
    pub fn can_add_class_schema(
```

2019-12-24 11:08 UTC, siman commented on src/permissions.rs
> +                    Err("NotInEntityPermissionsUpdateSet")
```suggestion
                    Err("BasePrincipalIsNotInEntityPermissionsUpdateSet")
```

2019-12-24 11:08 UTC, siman commented on src/lib.rs
> +                                "NotEnityOwner"
```suggestion
                                "PrincipalIsNotEnityOwner"
```

2019-12-24 11:08 UTC, siman commented on src/lib.rs
> +                                _ => Err("NotEnityOwner"),
```suggestion
                                _ => Err("PrincipalIsNotEnityOwner"),
```

2019-12-24 11:08 UTC, siman commented on src/lib.rs
> +                        "NotEnityOwner"
```suggestion
                        "PrincipalIsNotEnityOwner"
```

2019-12-24 11:08 UTC, siman commented on src/lib.rs
> +                        _ => Err("NotEnityOwner"),
```suggestion
                        _ => Err("PrincipalIsNotEnityOwner"),
```

2019-12-24 11:08 UTC, siman commented on src/principles.rs
> +    Owner,
Should be called `EntityOwner` as in `DerivedPrincipal`?
```suggestion
    EntityOwner,
```

2019-12-24 11:08 UTC, siman commented on src/permissions.rs
> +    /// Permissions that are applied to entities of this class, defines who in addition to
```suggestion
    /// Permissions that are applied to entities of this class, define who in addition to
```

2019-12-24 11:08 UTC, siman commented on src/constraint.rs
> +    /// Only a set of entities of type ClassId and from the specified property index can reference the class.
This comment seems a bit wrong because here you specify what exact properties (property indexes) on what exact class can refer to this class. There is nothing about entity in this field.

2019-12-24 11:08 UTC, siman commented on src/constraint.rs
> +/// Pointer to a specific property of entities of a specfic class.
There is nothing about entity in this structure. You only refer to class and property index.
```suggestion
/// Pointer to a specific property of a specific class.
```

2019-12-24 11:08 UTC, siman commented on src/constraint.rs
> +/// Pointer to a specific property of entities of a specfic class.
I mean that property is declared in class, whereas property value is a part of an entity.
So, in this case, it's just a property of a class.

2019-12-24 11:08 UTC, siman commented on src/lib.rs
> +            "ClassIdDoesNotExist"
```suggestion
            "ClassPermissionsNotFoundByClassId"
```

2019-12-24 11:08 UTC, siman commented on src/principles.rs
> +    GroupMember(GroupId),
```suggestion
    Group(GroupId),
    // or even `ExternalGroup` to emphasize that this group is defined out of the scope of this module:
    ExternalGroup(GroupId),
```

2020-01-07 13:38 UTC, mnaamani commented on src/permissions.rs
> +    pub delete: EntityPrincipalSet<AccountId, GroupId>,
done

2020-01-07 13:38 UTC, mnaamani commented on src/tests.rs
> +            delete: EntityPrincipalSet::new(),
done

2020-01-07 14:10 UTC, mnaamani commented on src/constraint.rs
> +    /// Only a set of entities of type ClassId and from the specified property index can reference the class.
fixed in 16c068976fd4a7a692c2a35661fba2298267ee41

2020-01-07 14:17 UTC, mnaamani commented on src/principles.rs
> +    Owner,
outdated

2020-01-07 14:21 UTC, mnaamani commented on src/principles.rs
> +    GroupMember(GroupId),
outdated

2020-01-07 14:29 UTC, mnaamani commented on src/permissions.rs
> +                    Err("NotInEntityPermissionsUpdateSet")
renaming to `CredentialIsNotInEntityPermissionsUpdateSet`

2020-01-07 14:30 UTC, mnaamani commented on src/lib.rs
> +                                "NotEnityOwner"
outdated

2020-01-07 14:30 UTC, mnaamani commented on src/lib.rs
> +                                _ => Err("NotEnityOwner"),
outdated

2020-01-07 14:30 UTC, mnaamani commented on src/lib.rs
> +                        "NotEnityOwner"
outaded

2020-01-07 14:30 UTC, mnaamani commented on src/lib.rs
> +                        _ => Err("NotEnityOwner"),
outdated

2020-01-07 14:34 UTC, mnaamani commented on src/lib.rs
> +            "ClassIdDoesNotExist"
fixed in 8c279444ab63e0a71f9ce742492c834b81c739cf

2020-01-07 14:35 UTC, mnaamani commented
Incorporated most of your suggestions @siman although since the review was a bit out of date some of the review comments were not relevant any more.
Ready for final review.

2020-01-07 14:59 UTC, mnaamani commented
Also just a final thought, since we are not going to invest more in features for this module beyond rome release there is no point making any additional improvements, so only bug fixes really.

2020-01-08 12:22 UTC, siman approved these changes

2020-01-10 11:16 UTC, merged